---
- name: Static app deployment
  hosts: all
  become: yes
  tasks:
    - name: Install software
      apt:
        name: nginx
        update_cache: yes
      
    - name: Git clone
      git:
        repo: https://github.com/preciousakpan/stop-watch-app.git
        dest: /var/www/html/static

    - name: copy nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
